# Generated by Django 3.1.1 on 2020-09-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_product_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='producto', verbose_name='Imagen 4'),
        ),
    ]
